CXX			= g++
#--------------------------------------------------------------------
DEFINES		= -DSQLITE_THREADSAFE=2 -DSQLITE_ENABLE_COLUMN_METADATA=1
CCOPTIONS	= -std=c++11 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCLUDES	= -I. -I../sqlite3 -I../testmain/include -I/usr/include
LDOPTIONS	=
LIBS		= -lpthread
#--------------------------------------------------------------------
PROG	= sample
OBJS	= runner.o \
		  main.o
#--------------------------------------------------------------------
override CFLAGS := $(CFLAGS) $(CCOPTIONS) $(INCLUDES) $(DEFINES)
override CXXFLAGS := $(CXXFLAGS) $(CCOPTIONS) $(INCLUDES) $(DEFINES)
LDFLAGS := $(LDOPTIONS)
LDLIBS	=
#--------------------------------------------------------------------
all: $(OBJS) $(PROG)
#--------------------------------------------------------------------
$(PROG): $(OBJS) $(LDLIBS)
	$(CXX) $(CFLAGS) ./obj/*.o $(LDFLAGS) $(LDLIBS) $(LIBS) -o $@
#--------------------------------------------------------------------
$(OBJS):
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -c $*.cpp -o obj/$@
#--------------------------------------------------------------------
