CXX			= g++
#--------------------------------------------------------------------
DEFINES		=
CCOPTIONS	= -std=c++11 -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCLUDES	= -I. -I../testmain/include -I/usr/include
LDOPTIONS	=
LIBS		=
#--------------------------------------------------------------------
OBJS	= \
		  TestUtility.o \
		  Test003.o \
		  Test002.o \
		  Test001.o \
		  Test.o
#--------------------------------------------------------------------
override CFLAGS := $(CFLAGS) $(CCOPTIONS) $(INCLUDES) $(DEFINES)
override CXXFLAGS := $(CXXFLAGS) $(CCOPTIONS) $(INCLUDES) $(DEFINES)
LDFLAGS := $(LDOPTIONS)
LDLIBS	=
#--------------------------------------------------------------------
all: $(OBJS)
#--------------------------------------------------------------------
$(OBJS):
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -c ../testmain/src/$*.cpp -o obj/$@
#--------------------------------------------------------------------
